[versions]
agp = "8.11.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
androidx-lifecycle = "2.9.1"
compose-multiplatform = "1.8.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
lifecycleViewmodelCompose = "2.9.1"
logbackClassic = "1.5.18"
materialKolor = "3.0.0"
napier = "2.7.1"
slf4jApi = "2.0.17"
buildconfig = "5.6.7"
appcompat = "1.7.1"
uiAndroid = "1.8.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
